name: Collect Purdue MBB Headlines

on:
  schedule:
    - cron: "*/15 * * * *"   # every 15 minutes
  workflow_dispatch:
  push:
    paths:
      - "src/feeds.yml"
      - "collect.py"

permissions:
  contents: write

jobs:
  collect-headlines:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repo
        uses: actions/checkout@v4
        with:
          persist-credentials: true

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.x"

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install feedparser pyyaml

      - name: Run scraper
        run: |
          python collect.py

      - name: Commit updated items.json
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

          git add static/teams/purdue-mbb/items.json
          git commit -m "Update items.json [skip ci]" || echo "No changes to commit"
          git push