name: collect-purdue-mbb

on:
  schedule:
    - cron: "0 * * * *"  # hourly
  workflow_dispatch:

jobs:
  collect:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          persist-credentials: false

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.x"

      - name: Run collector
        run: |
          python3 tools/collect.py

      - name: Commit & push updated JSON
        run: |
          git config user.name "sports-app-bot"
          git config user.email "actions@github"
          git add static/teams/purdue-mbb/items.json
          if git diff --cached --quiet; then
            echo "No changes."
          else
            git commit -m "auto: update Purdue MBB feed"
            git push https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git HEAD:main
          fi