name: collect-purdue-mbb

on:
  schedule:
    # run every 30 minutes
    - cron: "*/30 * * * *"
  # allow manual trigger in Actions tab
  workflow_dispatch:

# allow the workflow to commit/push changes
permissions:
  contents: write

jobs:
  collect:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout full repo with write credentials
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          persist-credentials: true
          fetch-depth: 0

      # 2. Set up Python
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.x"

      # 3. Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install feedparser requests beautifulsoup4 python-dateutil

      # 4. Run collector script
      - name: Run collector
        run: |
          echo "Running Purdue MBB article collector..."
          python tools/collect.py

      # 5. Commit & push JSON if changed
      - name: Commit and push updates
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          echo "Checking for changes..."

          git config user.name "sports-app-bot"
          git config user.email "actions@users.noreply.github.com"

          git add static/teams/purdue-mbb/items.json || true

          if ! git diff --cached --quiet; then
            echo "Changes detected — committing."
            git commit -m "auto: update Purdue MBB feed"
            git pull --rebase origin main || true
            git push origin main
          else
            echo "No feed changes to commit."
          fi

      # 6. Done
      - name: Done
        run: echo "✅ Collector finished successfully."