name: collect-purdue-mbb

on:
  schedule:
    - cron: "*/30 * * * *"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  collect:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          persist-credentials: true
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.x"

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install feedparser requests beautifulsoup4

      - name: Run collector
        run: |
          python tools/collect.py

      - name: Commit & push (if changes)
        run: |
          git config user.name "sports-app-bot"
          git config user.email "actions@users.noreply.github.com"
          git add static/teams/purdue-mbb/items.json
          if ! git diff --cached --quiet; then
            git commit -m "auto: update Purdue MBB items.json"
            git pull --rebase origin main || true
            git push origin main
          else
            echo "No feed changes to commit."
          fi